export const lOGING_LOADING = "LOGGING_LOADING";
export const LOGGING_SUCCESS = "LOGGING_SUCCESS";
export const LOGGING_ERROR = "LOGGING_ERROR";

export const REMOVE_AUTH = "REMOVE_AUTH";

export const GET_ALL_LOANS_LOADING = "GET_ALL_LOANS_LOADING";
export const GET_ALL_LOANS_SUCCESS = "GET_ALL_LOANS_SUCCESS";
export const GET_ALL_LOANS_ERROR = "GET_ALL_LOANS_ERROR";

export const GET_CREDIT_SCORE_LOADING = "GET_CREDIT_SCORE_LOADING";
export const GET_CREDIT_SCORE_SUCCESS = "GET_CREDIT_SCORE_SUCCESS";
export const GET_CREDIT_SCORE_ERROR = "GET_CREDIT_SCORE_ERROR";

export const CREATE_CUSTOMER_LOADING = "CREATE_CUSTOMER_LOADING";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_ERROR = "CREATE_CUSTOMER_ERROR";

export const CREATE_LOAN_ACCOUNT_LOADING = "CREATE_LOAN_ACCOUNT_LOADING";
export const CREATE_LOAN_ACCOUNT_SUCCESS = "CREATE_LOAN_ACCOUNT_SUCCESS";
export const CREATE_LOAN_ACCOUNT_ERROR = "CREATE_LOAN_ACCOUNT_ERROR";
